// Generated by CoffeeScript 1.6.2
(function() {
  var root,
    _this = this;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.disable_cf = function(el_nbr, option) {
    var color;

    if (option) {
      color = "#eeeeee";
    } else {
      color = "#141414";
    }
    return $("#item-deformField" + el_nbr).css("color", color);
  };

}).call(this);
